
package ec.edu.espe.safestore.view.panels;

import ec.edu.espe.safestore.controller.StockController;
import ec.edu.espe.safestore.model.Product;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Alexander Tipantiza, The Softwarriors, @ESPE
 */
public class PnlStock extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    private StockController stockController;

    public PnlStock() {
        stockController = new StockController();
        initComponents();
        outputArea.setText("Stock Alerts Ready\n");
        loadSampleData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCheckAlerts = new javax.swing.JButton();
        btnGenerateOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock Alerts");

        btnCheckAlerts.setText("Check Alerts");
        btnCheckAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAlertsActionPerformed(evt);
            }
        });

        btnGenerateOrder.setText("Generate Order");
        btnGenerateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateOrderActionPerformed(evt);
            }
        });

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Product", "Stock", "Min Stock", "Status"}
        ));
        jScrollPane1.setViewportView(tblStock);

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane2.setViewportView(outputArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheckAlerts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerateOrder)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckAlerts)
                    .addComponent(btnGenerateOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadSampleData() {
        tableModel = (DefaultTableModel) tblStock.getModel();
        List<Product> lowStock = stockController.getLowStockProducts();
        if (lowStock.isEmpty()) {
            tableModel.addRow(new Object[]{101, "Paper Plate 25cm", 45, 50, "CRITICAL"});
            tableModel.addRow(new Object[]{102, "Plastic Cup 12oz", 80, 60, "OK"});
            tableModel.addRow(new Object[]{103, "Disposable Fork", 30, 40, "CRITICAL"});
        } else {
            for (Product p : lowStock) {
                String status = p.getStock() <= p.getMinStock() ? "CRITICAL" : "OK";
                tableModel.addRow(new Object[]{p.getId(), p.getName(), p.getStock(), p.getMinStock(), status});
            }
        }
    }

    private void btnCheckAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAlertsActionPerformed
        outputArea.append("\n=== STOCK ALERTS ===\n");
        boolean hasAlerts = false;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if (tableModel.getValueAt(i, 4).toString().equals("CRITICAL")) {
                outputArea.append("  [CRITICAL] " + tableModel.getValueAt(i, 1) + " - Stock: " + tableModel.getValueAt(i, 2) + " (Min: " + tableModel.getValueAt(i, 3) + ")\n");
                hasAlerts = true;
            }
        }
        if (!hasAlerts) {
            outputArea.append("  No stock alerts at this time\n");
        }
        outputArea.append("\n");
    }//GEN-LAST:event_btnCheckAlertsActionPerformed

    private void btnGenerateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateOrderActionPerformed
        outputArea.append("\n=== SUGGESTED ORDER LIST ===\n");
        boolean hasOrders = false;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if (tableModel.getValueAt(i, 4).toString().equals("CRITICAL")) {
                int stock = Integer.parseInt(tableModel.getValueAt(i, 2).toString());
                int minStock = Integer.parseInt(tableModel.getValueAt(i, 3).toString());
                int suggested = minStock * 2 - stock;
                if (suggested < 0) suggested = minStock;
                outputArea.append("  " + tableModel.getValueAt(i, 1) + " - Order " + suggested + " units\n");
                hasOrders = true;
            }
        }
        if (!hasOrders) {
            outputArea.append("  No orders needed\n");
        }
        outputArea.append("\n");
        JOptionPane.showMessageDialog(this, "Order list generated - Check console");
    }//GEN-LAST:event_btnGenerateOrderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAlerts;
    private javax.swing.JButton btnGenerateOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JTable tblStock;
    // End of variables declaration//GEN-END:variables
}