/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.Maze.view;
import ec.edu.espe.Maze.model.*;
import ec.edu.espe.Maze.controller.*;
import java.awt.Graphics;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Angie Nacato, Error 404, @ESPE
 */
public class MazeGUI extends javax.swing.JFrame implements MazeRenderer {
    private Maze maze;
    private PathController controller;

    /**
     * Creates new form MazeGUI
     */
    public MazeGUI() {
        initComponents();
        this.setSize(600, 650);
        this.setLocationRelativeTo(null);
    }
    public void setController(PathController controller) {
        this.controller = controller;
    }

    @Override
    public void render(Maze maze) {
        this.maze = maze;
        this.repaint();
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        
        if (maze == null) return;
        
        int size = 40; 
        int offsetX = 100; 
        int offsetY = 60;  
        
        g.setColor(Color.BLACK);
        
        for (int x = 0; x < maze.getWidth(); x++) {
            for (int y = 0; y < maze.getHeight(); y++) {
                int drawX = offsetX + (x * size);
                int drawY = offsetY + (y * size);
                
                if (maze.hasHorizontalWall(x, y))     g.drawLine(drawX, drawY, drawX + size, drawY);               
                if (maze.hasHorizontalWall(x, y + 1)) g.drawLine(drawX, drawY + size, drawX + size, drawY + size); 
                if (maze.hasVerticalWall(x, y))       g.drawLine(drawX, drawY, drawX, drawY + size);               
                if (maze.hasVerticalWall(x + 1, y))   g.drawLine(drawX + size, drawY, drawX + size, drawY + size); 
            }
        }
        
        g.setColor(Color.RED);
        g.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        g.drawString("S", offsetX + 15, offsetY + 25);
        
        int lastX = offsetX + ((maze.getWidth() - 1) * size);
        int lastY = offsetY + ((maze.getHeight() - 1) * size);
        g.drawString("E", lastX + 15, lastY + 25);
        
        if (maze.getPlayer() != null && maze.getPlayer().getCurrentRoom() != null) {
            Room current = maze.getPlayer().getCurrentRoom();
            g.setColor(Color.BLUE);
            g.fillOval(offsetX + (current.getX() * size) + 10, offsetY + (current.getY() * size) + 10, 20, 20);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMaze = new javax.swing.JPanel();
        btnNorth = new javax.swing.JButton();
        btnSouth = new javax.swing.JButton();
        btnEast = new javax.swing.JButton();
        btnWest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNorth.setText("North");
        btnNorth.addActionListener(this::btnNorthActionPerformed);

        btnSouth.setText("South");
        btnSouth.addActionListener(this::btnSouthActionPerformed);

        btnEast.setText("East");
        btnEast.addActionListener(this::btnEastActionPerformed);

        btnWest.setText("West");
        btnWest.addActionListener(this::btnWestActionPerformed);

        javax.swing.GroupLayout pnlMazeLayout = new javax.swing.GroupLayout(pnlMaze);
        pnlMaze.setLayout(pnlMazeLayout);
        pnlMazeLayout.setHorizontalGroup(
            pnlMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMazeLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(btnWest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSouth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNorth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEast)
                .addGap(184, 184, 184))
        );
        pnlMazeLayout.setVerticalGroup(
            pnlMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMazeLayout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addGroup(pnlMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMazeLayout.createSequentialGroup()
                        .addGroup(pnlMazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEast)
                            .addComponent(btnWest))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMazeLayout.createSequentialGroup()
                        .addComponent(btnNorth)
                        .addGap(18, 18, 18)
                        .addComponent(btnSouth)
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMaze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMaze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSouthActionPerformed
        if (controller != null) {
        controller.movePlayer("South"); 
        }
    }//GEN-LAST:event_btnSouthActionPerformed

    private void btnNorthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNorthActionPerformed
        if (controller != null) {
        controller.movePlayer("North"); 
        }
    }//GEN-LAST:event_btnNorthActionPerformed

    private void btnEastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEastActionPerformed
        if (controller != null) {
        controller.movePlayer("East"); 
        }
    }//GEN-LAST:event_btnEastActionPerformed

    private void btnWestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWestActionPerformed
        if (controller != null) {
        controller.movePlayer("West"); 
        }
    }//GEN-LAST:event_btnWestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    System.out.println("1. Generating maze...");
                    Maze maze = new Maze(10, 10);
                    maze.generate(10, 10);

                    System.out.println("2. Placing player...");
                    Room startRoom = maze.getRooms().get(0);
                    Player player = new Player(startRoom);
                    maze.setPlayer(player);

                    System.out.println("3. Creating window...");
                    MazeGUI gui = new MazeGUI();

                    System.out.println("4. Connecting controller...");
                    PathController controller = new PathController(maze, gui);
                    gui.setController(controller);

                    System.out.println("5. Rendering...");
                    gui.render(maze);
                    gui.setVisible(true);

                    System.out.println("6. Success!");
                } catch (Exception e) {
                    System.out.println("ERROR FOUND: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEast;
    private javax.swing.JButton btnNorth;
    private javax.swing.JButton btnSouth;
    private javax.swing.JButton btnWest;
    private javax.swing.JPanel pnlMaze;
    // End of variables declaration//GEN-END:variables
}
