/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.safestore.view;

/**
 *
 * @author Adrian Vizcaino <The-Softwarriors at ESPE>
 */
public class FrmMenuCashier extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuCashier.class.getName());

    /**
     * Creates new form FrmMenuCashier
     */
    public FrmMenuCashier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemNewCR = new javax.swing.JMenuItem();
        ItemCancelCR = new javax.swing.JMenuItem();
        ItemDailyCR = new javax.swing.JMenuItem();
        ItemCloseCR = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ItemDepositCS = new javax.swing.JMenuItem();
        ItemWithdrawCS = new javax.swing.JMenuItem();
        ItemSafeCS = new javax.swing.JMenuItem();
        ItemTransactionCS = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ItemNewMS = new javax.swing.JMenuItem();
        ItemSalesMS = new javax.swing.JMenuItem();
        ItemDailyMS = new javax.swing.JMenuItem();
        ItemGenerateMS = new javax.swing.JMenuItem();
        ItemCloseMS = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jLabel1.setText("Safe Store");

        jMenu1.setText("Cash Register");

        ItemNewCR.setText("New Sale");
        jMenu1.add(ItemNewCR);

        ItemCancelCR.setText("Cancel Sale");
        jMenu1.add(ItemCancelCR);

        ItemDailyCR.setText("Daily Sales");
        jMenu1.add(ItemDailyCR);

        ItemCloseCR.setText("Close Register");
        jMenu1.add(ItemCloseCR);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cash Safe");

        ItemDepositCS.setText("Deposit Cash");
        jMenu2.add(ItemDepositCS);

        ItemWithdrawCS.setText("Withdraw Cash");
        jMenu2.add(ItemWithdrawCS);

        ItemSafeCS.setText("Safe Balance");
        jMenu2.add(ItemSafeCS);

        ItemTransactionCS.setText("Transaction History");
        jMenu2.add(ItemTransactionCS);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Make Sale");

        ItemNewMS.setText("New Sale");
        ItemNewMS.addActionListener(this::ItemNewMSActionPerformed);
        jMenu5.add(ItemNewMS);

        ItemSalesMS.setText("Sales History");
        jMenu5.add(ItemSalesMS);

        ItemDailyMS.setText("Daily Sales");
        jMenu5.add(ItemDailyMS);

        ItemGenerateMS.setText("Generate Ticket");
        jMenu5.add(ItemGenerateMS);

        ItemCloseMS.setText("Close Register");
        jMenu5.add(ItemCloseMS);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemNewMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNewMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemNewMSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuCashier().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCancelCR;
    private javax.swing.JMenuItem ItemCloseCR;
    private javax.swing.JMenuItem ItemCloseMS;
    private javax.swing.JMenuItem ItemDailyCR;
    private javax.swing.JMenuItem ItemDailyMS;
    private javax.swing.JMenuItem ItemDepositCS;
    private javax.swing.JMenuItem ItemGenerateMS;
    private javax.swing.JMenuItem ItemNewCR;
    private javax.swing.JMenuItem ItemNewMS;
    private javax.swing.JMenuItem ItemSafeCS;
    private javax.swing.JMenuItem ItemSalesMS;
    private javax.swing.JMenuItem ItemTransactionCS;
    private javax.swing.JMenuItem ItemWithdrawCS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
