/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.safestore.view;

/**
 *
 * @author Adrian Vizcaino <The-Softwarriors at ESPE>
 */
public class FrmMenuManager extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuManager.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenuManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ItemManagePrd = new javax.swing.JMenu();
        ItemAddPrd = new javax.swing.JMenuItem();
        ItemDeletePrd = new javax.swing.JMenuItem();
        ItemUploadPrd = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ItemCreateCom = new javax.swing.JMenuItem();
        ItemDeleteCom = new javax.swing.JMenuItem();
        ItemUploadCom = new javax.swing.JMenuItem();
        ItemManageCom = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ItemAddCrd = new javax.swing.JMenuItem();
        ItemActiveCrd = new javax.swing.JMenuItem();
        ItemPendingCrd = new javax.swing.JMenuItem();
        ItemOverdueCrd = new javax.swing.JMenuItem();
        ItemManagementExp = new javax.swing.JMenu();
        ItemDateExp = new javax.swing.JMenuItem();
        ItemExpiringExp = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        ItemSalesRep = new javax.swing.JMenuItem();
        ItemPurchaseRep = new javax.swing.JMenuItem();
        ItemInventoryRep = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        ItemAvailableSto = new javax.swing.JMenuItem();
        ItemStatusSto = new javax.swing.JMenuItem();
        ItemViewSup = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        ItemUpdateSup = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        ItemNewRes = new javax.swing.JMenuItem();
        ItemListRes = new javax.swing.JMenuItem();
        ItemCheckRes = new javax.swing.JMenuItem();
        ItemHistoryRes = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu10.setText("jMenu10");

        jMenu1.setText("File");
        jMenuBar4.add(jMenu1);

        jMenu14.setText("Edit");
        jMenuBar4.add(jMenu14);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        jLabel1.setText("Safe Store");

        ItemManagePrd.setText("Products");

        ItemAddPrd.setText("Add Product");
        ItemManagePrd.add(ItemAddPrd);

        ItemDeletePrd.setText("Delete Product");
        ItemManagePrd.add(ItemDeletePrd);

        ItemUploadPrd.setText("Modify Product");
        ItemManagePrd.add(ItemUploadPrd);

        jMenuItem2.setText("Manage Products");
        ItemManagePrd.add(jMenuItem2);

        jMenuBar1.add(ItemManagePrd);

        jMenu2.setText("Combos");

        ItemCreateCom.setText("Create Combo");
        jMenu2.add(ItemCreateCom);

        ItemDeleteCom.setText("Delete Combo");
        jMenu2.add(ItemDeleteCom);

        ItemUploadCom.setText("Modify Combo");
        jMenu2.add(ItemUploadCom);

        ItemManageCom.setText("Manage Combo");
        ItemManageCom.addActionListener(this::ItemManageComActionPerformed);
        jMenu2.add(ItemManageCom);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Credits");

        ItemAddCrd.setText("Add Loan");
        jMenu5.add(ItemAddCrd);

        ItemActiveCrd.setText("Active Loans");
        jMenu5.add(ItemActiveCrd);

        ItemPendingCrd.setText("Pending Payments");
        jMenu5.add(ItemPendingCrd);

        ItemOverdueCrd.setText("Overdue Payments");
        jMenu5.add(ItemOverdueCrd);

        jMenuBar1.add(jMenu5);

        ItemManagementExp.setText("Expiration");

        ItemDateExp.setText("Expiration Dates");
        ItemManagementExp.add(ItemDateExp);

        ItemExpiringExp.setText("Expiring Items");
        ItemManagementExp.add(ItemExpiringExp);

        jMenuItem3.setText("Expiry Management");
        ItemManagementExp.add(jMenuItem3);

        jMenuBar1.add(ItemManagementExp);

        jMenu9.setText("Report");

        ItemSalesRep.setText("Sales Report");
        jMenu9.add(ItemSalesRep);

        ItemPurchaseRep.setText("Purchase Report");
        jMenu9.add(ItemPurchaseRep);

        ItemInventoryRep.setText("Inventory Report");
        jMenu9.add(ItemInventoryRep);

        jMenuBar1.add(jMenu9);

        jMenu11.setText("Stock");

        ItemAvailableSto.setText("Available Stock");
        jMenu11.add(ItemAvailableSto);

        ItemStatusSto.setText("Stock Status");
        jMenu11.add(ItemStatusSto);

        jMenuBar1.add(jMenu11);

        ItemViewSup.setText("Suppliers");

        jMenuItem4.setText("Register Suplier");
        ItemViewSup.add(jMenuItem4);

        jMenuItem5.setText("View Suppliers");
        ItemViewSup.add(jMenuItem5);

        ItemUpdateSup.setText("Update Supplier");
        ItemViewSup.add(ItemUpdateSup);

        jMenuBar1.add(ItemViewSup);

        jMenu13.setBackground(new java.awt.Color(153, 153, 153));
        jMenu13.setText("Reservations");

        ItemNewRes.setText("New Reservation");
        jMenu13.add(ItemNewRes);

        ItemListRes.setText("Reservation List");
        jMenu13.add(ItemListRes);

        ItemCheckRes.setText("Check Availabilityy");
        jMenu13.add(ItemCheckRes);

        ItemHistoryRes.setText("Reservation History");
        jMenu13.add(ItemHistoryRes);

        jMenuBar1.add(jMenu13);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemManageComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemManageComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemManageComActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuManager().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemActiveCrd;
    private javax.swing.JMenuItem ItemAddCrd;
    private javax.swing.JMenuItem ItemAddPrd;
    private javax.swing.JMenuItem ItemAvailableSto;
    private javax.swing.JMenuItem ItemCheckRes;
    private javax.swing.JMenuItem ItemCreateCom;
    private javax.swing.JMenuItem ItemDateExp;
    private javax.swing.JMenuItem ItemDeleteCom;
    private javax.swing.JMenuItem ItemDeletePrd;
    private javax.swing.JMenuItem ItemExpiringExp;
    private javax.swing.JMenuItem ItemHistoryRes;
    private javax.swing.JMenuItem ItemInventoryRep;
    private javax.swing.JMenuItem ItemListRes;
    private javax.swing.JMenuItem ItemManageCom;
    private javax.swing.JMenu ItemManagePrd;
    private javax.swing.JMenu ItemManagementExp;
    private javax.swing.JMenuItem ItemNewRes;
    private javax.swing.JMenuItem ItemOverdueCrd;
    private javax.swing.JMenuItem ItemPendingCrd;
    private javax.swing.JMenuItem ItemPurchaseRep;
    private javax.swing.JMenuItem ItemSalesRep;
    private javax.swing.JMenuItem ItemStatusSto;
    private javax.swing.JMenuItem ItemUpdateSup;
    private javax.swing.JMenuItem ItemUploadCom;
    private javax.swing.JMenuItem ItemUploadPrd;
    private javax.swing.JMenu ItemViewSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
