/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.shoppingstore.view;

/**
 *
 * @author Anthony Aimacaña, MKA programer, @ESPE
 */
public class FrmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmQuit = new javax.swing.JMenuItem();
        Products = new javax.swing.JMenu();
        itmBuy = new javax.swing.JMenuItem();
        itmSell = new javax.swing.JMenuItem();
        itmAddToStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmGenerateReport = new javax.swing.JMenuItem();
        itmGeneratePdf = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itmManage = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("System");

        itmQuit.setText("Quit");
        itmQuit.addActionListener(this::itmQuitActionPerformed);
        jMenu1.add(itmQuit);

        jMenuBar1.add(jMenu1);

        Products.setText("Products");

        itmBuy.setText("Buy");
        Products.add(itmBuy);

        itmSell.setText("Sell");
        Products.add(itmSell);

        itmAddToStock.setText("Add to stock");
        Products.add(itmAddToStock);

        jMenuBar1.add(Products);

        jMenu3.setText("Report");

        itmGenerateReport.setText("Generata");
        itmGenerateReport.addActionListener(this::itmGenerateReportActionPerformed);
        jMenu3.add(itmGenerateReport);

        itmGeneratePdf.setText("Pdf");
        jMenu3.add(itmGeneratePdf);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Customers");

        itmManage.setText("Manage");
        itmManage.addActionListener(this::itmManageActionPerformed);
        jMenu4.add(itmManage);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Help");

        itmAbout.setText("About");
        itmAbout.addActionListener(this::itmAboutActionPerformed);
        jMenu2.add(itmAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmQuitActionPerformed

    private void itmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAboutActionPerformed

    private void itmGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGenerateReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmGenerateReportActionPerformed

    private void itmManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmManageActionPerformed
        FrmCustomer frmCustomer = new FrmCustomer();
        this.dispose();
        frmCustomer.setVisible(true);
    }//GEN-LAST:event_itmManageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Products;
    private javax.swing.JMenuItem itmAbout;
    private javax.swing.JMenuItem itmAddToStock;
    private javax.swing.JMenuItem itmBuy;
    private javax.swing.JMenuItem itmGeneratePdf;
    private javax.swing.JMenuItem itmGenerateReport;
    private javax.swing.JMenuItem itmManage;
    private javax.swing.JMenuItem itmQuit;
    private javax.swing.JMenuItem itmSell;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
