/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.oopconcepts.view;

import ec.edu.espe.oopconcepts.controller.AnimalController;
import ec.edu.espe.oopconcepts.model.*;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Codena, CodeBreakers, @ESPE
 */
public class FrmAnimals extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAnimals.class.getName());

    /**
     * Creates new form FrmAnimals
     */
    public FrmAnimals() {
        initComponents();

        loadAnimalsTable();
    }

    public void clear() {

        txtId.setText("");
        txtBreed.setText("");
        txtBornOnDate.setText("");
        txtWeight.setText("");

        cbxIsMolting.setSelected(false);
        sldNumberOfEggs.setValue(0);

        cbxIsProducingMilk.setSelected(false);

        txtLastShearing.setText("");

        txtIdealWeight.setText("");
    }

    private void loadAnimalsTable() {

        AnimalController controller = new AnimalController();
        ArrayList<FarmAnimal> animals = controller.read();

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Type");
        model.addColumn("Breed");
        model.addColumn("Birth");
        model.addColumn("Weight");

        for (FarmAnimal animal : animals) {

            model.addRow(new Object[]{
                animal.getId(),
                animal.getClass().getSimpleName(),
                animal.getBreed(),
                animal.getBornOnDate(),
                animal.getWeight()

            });

        }
        tblAnimals.setModel(model);

    }

    private void loadAnimal(FarmAnimal animal) {

        txtId.setText(String.valueOf(animal.getId()));
        txtBreed.setText(animal.getBreed());
        txtWeight.setText(String.valueOf(animal.getWeight()));
        txtBornOnDate.setText(animal.getBornOnDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        if (animal instanceof Chicken) {

            Chicken chicken = (Chicken) animal;

            cmbType.setSelectedItem("Chicken");
            cbxIsMolting.setSelected(chicken.isMolting());
            sldNumberOfEggs.setValue(chicken.getNumberOfEggs());

        } else if (animal instanceof Pig) {

            Pig pig = (Pig) animal;

            cmbType.setSelectedItem("Pig");
            txtIdealWeight.setText(String.valueOf(pig.getIdealWeight()));

        } else if (animal instanceof Cow) {

            Cow cow = (Cow) animal;

            cmbType.setSelectedItem("Cow");
            cbxIsProducingMilk.setSelected(cow.isIsProducingMilk());

        } else if (animal instanceof Sheep) {

            Sheep sheep = (Sheep) animal;

            cmbType.setSelectedItem("Sheep");
            txtLastShearing.setText(sheep.getLastShearing().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        }

    }

    private FarmAnimal createAnimalFromForm() {

        String type = cmbType.getSelectedItem().toString();

        int id = Integer.parseInt(txtId.getText());
        String breed = txtBreed.getText();
        float weight = Float.parseFloat(txtWeight.getText());

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
        LocalDate bornOnDate = LocalDate.parse(txtBornOnDate.getText(), formatter);

        switch (type) {

            case "Chicken":
                return new Chicken(id, breed, bornOnDate, weight, cbxIsMolting.isSelected(), sldNumberOfEggs.getValue());

            case "Cow":
                return new Cow(id, breed, bornOnDate, weight, cbxIsProducingMilk.isSelected());

            case "Pig":
                float idealWeight = Float.parseFloat(txtIdealWeight.getText());
                return new Pig(id, breed, bornOnDate, weight, idealWeight);

            case "Sheep":
                LocalDate lastShearing = LocalDate.parse(txtLastShearing.getText(), formatter);
                return new Sheep(id, breed, bornOnDate, weight, lastShearing);

            default:
                return null;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSpecific = new javax.swing.JPanel();
        pnlChicken = new javax.swing.JPanel();
        cbxIsMolting = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sldNumberOfEggs = new javax.swing.JSlider();
        pnlCow = new javax.swing.JPanel();
        cbxIsProducingMilk = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        pnlSheep = new javax.swing.JPanel();
        txtLastShearing = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        pnlPig = new javax.swing.JPanel();
        txtIdealWeight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pnlGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBreed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBornOnDate = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimals = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSpecific.setLayout(new java.awt.CardLayout());

        jLabel7.setText("Molting:");

        jLabel8.setText("Number of Eggs:");

        javax.swing.GroupLayout pnlChickenLayout = new javax.swing.GroupLayout(pnlChicken);
        pnlChicken.setLayout(pnlChickenLayout);
        pnlChickenLayout.setHorizontalGroup(
            pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChickenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxIsMolting)
                    .addComponent(sldNumberOfEggs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChickenLayout.setVerticalGroup(
            pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChickenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cbxIsMolting))
                .addGap(18, 18, 18)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sldNumberOfEggs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlSpecific.add(pnlChicken, "Chicken");

        jLabel9.setText("Produce Milk:");

        javax.swing.GroupLayout pnlCowLayout = new javax.swing.GroupLayout(pnlCow);
        pnlCow.setLayout(pnlCowLayout);
        pnlCowLayout.setHorizontalGroup(
            pnlCowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCowLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxIsProducingMilk)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        pnlCowLayout.setVerticalGroup(
            pnlCowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCowLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlCowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cbxIsProducingMilk))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnlSpecific.add(pnlCow, "Cow");

        txtLastShearing.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        txtLastShearing.setToolTipText("MM/dd/yyyy");
        txtLastShearing.addActionListener(this::txtLastShearingActionPerformed);

        jLabel11.setText("Last Sheering:");

        javax.swing.GroupLayout pnlSheepLayout = new javax.swing.GroupLayout(pnlSheep);
        pnlSheep.setLayout(pnlSheepLayout);
        pnlSheepLayout.setHorizontalGroup(
            pnlSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSheepLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtLastShearing, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlSheepLayout.setVerticalGroup(
            pnlSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSheepLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastShearing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlSpecific.add(pnlSheep, "Sheep");

        jLabel10.setText("Ideal weight:");

        javax.swing.GroupLayout pnlPigLayout = new javax.swing.GroupLayout(pnlPig);
        pnlPig.setLayout(pnlPigLayout);
        pnlPigLayout.setHorizontalGroup(
            pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPigLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtIdealWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlPigLayout.setVerticalGroup(
            pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPigLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdealWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pnlSpecific.add(pnlPig, "Pig");

        jLabel1.setText("Animals");

        jLabel2.setText("Animal Type:");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chicken", "Cow", "Pig", "Sheep" }));
        cmbType.addActionListener(this::cmbTypeActionPerformed);

        jLabel3.setText("Id:");

        jLabel4.setText("Breed:");

        txtBornOnDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        txtBornOnDate.setToolTipText("MM/dd/yyyy");

        jLabel5.setText("Born On Date:");

        jLabel6.setText("Weight:");

        javax.swing.GroupLayout pnlGeneralLayout = new javax.swing.GroupLayout(pnlGeneral);
        pnlGeneral.setLayout(pnlGeneralLayout);
        pnlGeneralLayout.setHorizontalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeneralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId)
                    .addComponent(txtBreed)
                    .addComponent(txtBornOnDate)
                    .addComponent(txtWeight))
                .addGap(39, 39, 39))
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        pnlGeneralLayout.setVerticalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBornOnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBackToMenu.setText("Back To Menu");
        btnBackToMenu.addActionListener(this::btnBackToMenuActionPerformed);

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(58, 58, 58)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToMenu)
                .addGap(35, 35, 35))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnBackToMenu))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tblAnimals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnimals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnimalsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnimals);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSpecific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSpecific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        CardLayout card = (CardLayout) pnlSpecific.getLayout();

        String type = cmbType.getSelectedItem().toString();

        card.show(pnlSpecific, type);
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        AnimalController controller = new AnimalController();
        FarmAnimal animal = createAnimalFromForm();

        if (animal == null) {
            return;
        }

        if (controller.create(animal)) {

            JOptionPane.showMessageDialog(this, "Animal saved successfully.");
            loadAnimalsTable();
            clear();

        } else {
            JOptionPane.showMessageDialog(this, "An animal with ID " + animal.getId() + " already exists.");

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtLastShearingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastShearingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastShearingActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int id = Integer.parseInt(txtId.getText());
        AnimalController controller = new AnimalController();

        if (controller.delete(id)) {
            JOptionPane.showMessageDialog(this, "Animal deleted.");
            loadAnimalsTable();
            clear();

        } else {
            JOptionPane.showMessageDialog(this, "Animal was not deleted");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblAnimalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnimalsMouseClicked
        int row = tblAnimals.getSelectedRow();

        if (row == -1) {
            return;
        }

        int id = Integer.parseInt(tblAnimals.getValueAt(row, 0).toString());
        AnimalController controller = new AnimalController();
        FarmAnimal animal = controller.findById(id);

        if (animal != null) {
            loadAnimal(animal);
        }

    }//GEN-LAST:event_tblAnimalsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        FarmAnimal animal = createAnimalFromForm();
        AnimalController controller = new AnimalController();

        if (controller.update(animal)) {
            JOptionPane.showMessageDialog(this, "Animal updated successfully.");
            loadAnimalsTable();
            clear();

        } else {
            JOptionPane.showMessageDialog(this, "Animal was not updated.");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        FrmMenu frmMenu = new FrmMenu();
        frmMenu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAnimals().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbxIsMolting;
    private javax.swing.JCheckBox cbxIsProducingMilk;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlChicken;
    private javax.swing.JPanel pnlCow;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JPanel pnlPig;
    private javax.swing.JPanel pnlSheep;
    private javax.swing.JPanel pnlSpecific;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JSlider sldNumberOfEggs;
    private javax.swing.JTable tblAnimals;
    private javax.swing.JFormattedTextField txtBornOnDate;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdealWeight;
    private javax.swing.JFormattedTextField txtLastShearing;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
