/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.oopconcepts.view;

/**
 *
 * @author Daniel Codena, CodeBreakers, @ESPE
 */
public class FrmMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmManageAnimals = new javax.swing.JMenuItem();
        itmManageFood = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itmAnimalOperations = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Farm Chicken System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        itmExit.setText("Exit");
        itmExit.addActionListener(this::itmExitActionPerformed);
        jMenu1.add(itmExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Manage");

        itmManageAnimals.setText("Animals");
        itmManageAnimals.addActionListener(this::itmManageAnimalsActionPerformed);
        jMenu3.add(itmManageAnimals);

        itmManageFood.setText("Food");
        itmManageFood.addActionListener(this::itmManageFoodActionPerformed);
        jMenu3.add(itmManageFood);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Operations");

        itmAnimalOperations.setText("Animals");
        itmAnimalOperations.addActionListener(this::itmAnimalOperationsActionPerformed);
        jMenu4.add(itmAnimalOperations);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmManageAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmManageAnimalsActionPerformed
        FrmAnimals frmAnimals = new FrmAnimals();
        frmAnimals.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmManageAnimalsActionPerformed

    private void itmAnimalOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAnimalOperationsActionPerformed
        FrmAnimalOperations frmAnimalOperations = new FrmAnimalOperations();
        frmAnimalOperations.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAnimalOperationsActionPerformed

    private void itmManageFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmManageFoodActionPerformed
        FrmFood frmFood = new FrmFood();
        frmFood.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmManageFoodActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAnimalOperations;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmManageAnimals;
    private javax.swing.JMenuItem itmManageFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
