/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.shoppingstore.view;

/**
 *
 * @author Daniel Codena, CodeBreakers, @ESPE
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmBuy = new javax.swing.JMenuItem();
        itmSell = new javax.swing.JMenuItem();
        itmAddStock = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itmGenerateReports = new javax.swing.JMenuItem();
        itmGeneratePdf = new javax.swing.JMenuItem();
        Customers = new javax.swing.JMenu();
        itmManageCustomers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("System");

        itmQuit.setText("Quit");
        itmQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmQuitActionPerformed(evt);
            }
        });
        jMenu1.add(itmQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Products");

        itmBuy.setText("Buy");
        jMenu2.add(itmBuy);

        itmSell.setText("Sell");
        jMenu2.add(itmSell);

        itmAddStock.setText("Add to Stock");
        jMenu2.add(itmAddStock);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Reports");

        itmGenerateReports.setText("Generate");
        jMenu4.add(itmGenerateReports);

        itmGeneratePdf.setText("PDF");
        jMenu4.add(itmGeneratePdf);

        jMenuBar1.add(jMenu4);

        Customers.setText("Customers");

        itmManageCustomers.setText("Manage");
        itmManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmManageCustomersActionPerformed(evt);
            }
        });
        Customers.add(itmManageCustomers);

        jMenuBar1.add(Customers);

        jMenu3.setText("Help");

        itmAbout.setText("About");
        jMenu3.add(itmAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmQuitActionPerformed

    private void itmManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmManageCustomersActionPerformed
        FrmCustomer frmCustomer = new FrmCustomer();
        frmCustomer.setVisible(true);
    }//GEN-LAST:event_itmManageCustomersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Customers;
    private javax.swing.JMenuItem itmAbout;
    private javax.swing.JMenuItem itmAddStock;
    private javax.swing.JMenuItem itmBuy;
    private javax.swing.JMenuItem itmGeneratePdf;
    private javax.swing.JMenuItem itmGenerateReports;
    private javax.swing.JMenuItem itmManageCustomers;
    private javax.swing.JMenuItem itmQuit;
    private javax.swing.JMenuItem itmSell;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
