/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.farm.view;

import ec.edu.espe.farm.controller.FarmAnimalController;
import ec.edu.espe.farm.controller.FinanceController;
import ec.edu.espe.farm.model.FarmAnimal;
import ec.edu.espe.farm.model.FarmFinances;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Collahuazo
 */
public class FrmFinancialManagement extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmFinancialManagement.class.getName());

    /**
     * Creates new form FrmAnimalManagement
     */
    public FrmFinancialManagement() {
        initComponents();
        this.setLocationRelativeTo(null);
        refreshData();
        loadAnimals();
        
    }

    private void updateNetProfit() {
        try {
            double revenue = Double.parseDouble(txtTotalRevenue.getText().replace(",", "."));
            double costs = Double.parseDouble(txtTotalCosts.getText().replace(",", "."));
            double profit = revenue - costs;
            txtNetProfit.setText(String.format("%.2f", profit));
        } catch (NumberFormatException e) {
            txtNetProfit.setText("0.00");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegisterSale = new javax.swing.JButton();
        btnRegisterExpense = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        txtTotalRevenue = new javax.swing.JTextField();
        txtTotalCosts = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalCosts = new javax.swing.JLabel();
        txtNetProfit = new javax.swing.JTextField();
        cmbAnimals = new javax.swing.JComboBox<>();
        btnProcessBalance = new javax.swing.JButton();
        lblProductionStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenu.setText("Menu");
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Financial Management");

        btnRegisterSale.setText("Register Sale");
        btnRegisterSale.addActionListener(this::btnRegisterSaleActionPerformed);

        btnRegisterExpense.setText("Register Expense");
        btnRegisterExpense.addActionListener(this::btnRegisterExpenseActionPerformed);

        txtTotalRevenue.setText("0");

        txtTotalCosts.setText("0");
        txtTotalCosts.addActionListener(this::txtTotalCostsActionPerformed);

        lblAmount.setText("Amount:");

        jLabel3.setText("Total Revenue:");

        lblTotalCosts.setText("Total Costs:");

        cmbAnimals.addActionListener(this::cmbAnimalsActionPerformed);

        btnProcessBalance.setText("Process Balance");
        btnProcessBalance.addActionListener(this::btnProcessBalanceActionPerformed);

        lblProductionStatus.setText("Status: Pending...");

        jLabel2.setText("Net Profit:");

        jLabel4.setText("Select Animal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalCosts)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAmount)
                                        .addComponent(jLabel4)))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblProductionStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbAnimals, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalRevenue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalCosts, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNetProfit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegisterSale)
                        .addGap(33, 33, 33)
                        .addComponent(btnRegisterExpense)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcessBalance)))
                .addGap(32, 32, 32)
                .addComponent(btnMenu)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCosts))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNetProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addComponent(lblProductionStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterSale)
                    .addComponent(btnRegisterExpense)
                    .addComponent(btnProcessBalance)
                    .addComponent(btnMenu))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        FrmMain main = new FrmMain();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtTotalCostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCostsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCostsActionPerformed

    private void btnRegisterSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSaleActionPerformed
        float amount = Float.parseFloat(txtAmount.getText());
        FarmFinances finances = new FarmFinances();
        finances.setTotalRevenue(amount);
        finances.setTotalExpenses(0);
        FinanceController controller = new FinanceController();
        if (controller.saveFinances(finances)) {
            JOptionPane.showMessageDialog(this, "Sale recorded");
            refreshData();
        }
    }//GEN-LAST:event_btnRegisterSaleActionPerformed

    private void btnRegisterExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterExpenseActionPerformed
        float amount = Float.parseFloat(txtAmount.getText());
        FarmFinances finances = new FarmFinances();
        finances.setTotalRevenue(0);
        finances.setTotalExpenses(amount);

        FinanceController controller = new FinanceController();
        if (controller.saveFinances(finances)) {
            JOptionPane.showMessageDialog(this, "Recorded expense");
            refreshData();
        }
    }

    private void refreshData() {
        FinanceController controller = new FinanceController();
        java.util.List<org.bson.Document> history = controller.getFinanceHistory();
        double totalRevenue = 0;
        double totalExpenses = 0;

        for (org.bson.Document doc : history) {
            totalRevenue += doc.getDouble("totalRevenue");
            totalExpenses += doc.getDouble("totalExpenses");
        }

        double netProfit = totalRevenue - totalExpenses;

        txtTotalRevenue.setText(String.format("%.2f", totalRevenue));
        txtTotalCosts.setText(String.format("%.2f", totalExpenses));
        txtNetProfit.setText(String.format("%.2f", netProfit));
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFinancialManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FrmFinancialManagement().setVisible(true));
    }//GEN-LAST:event_btnRegisterExpenseActionPerformed

    private void btnProcessBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessBalanceActionPerformed
        FarmAnimal selectedAnimal = (FarmAnimal) cmbAnimals.getSelectedItem();
        if (selectedAnimal != null) {
            FarmFinances finances = new FarmFinances();
            finances.processAnimalBalance(selectedAnimal);
            JOptionPane.showMessageDialog(this, "Balance processed correctly for: " + selectedAnimal.getBreed());
            refreshData(); 
        } else {
            JOptionPane.showMessageDialog(this, "Please select an animal");
        }
    }//GEN-LAST:event_btnProcessBalanceActionPerformed
    
    private void cmbAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnimalsActionPerformed
        FarmAnimal selectedAnimal = (FarmAnimal) cmbAnimals.getSelectedItem();
        if (selectedAnimal != null) {
            FarmAnimalController controller = new FarmAnimalController();
         
            int ageInMonths = controller.calculateAgeInMonths(selectedAnimal);

            if (ageInMonths > 6) {
                lblProductionStatus.setText("Status: Production ready");
            } else {
                lblProductionStatus.setText("Status: In development");
            }
        }
    }
     private void loadAnimals() {
        FarmAnimalController animalController = new FarmAnimalController();
        java.util.List<FarmAnimal> animals = animalController.getAnimals(); 
        
        cmbAnimals.removeAllItems(); 
        for (FarmAnimal animal : animals) {
            cmbAnimals.addItem(animal);
        }
    
    }//GEN-LAST:event_cmbAnimalsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnProcessBalance;
    private javax.swing.JButton btnRegisterExpense;
    private javax.swing.JButton btnRegisterSale;
    private javax.swing.JComboBox<ec.edu.espe.farm.model.FarmAnimal> cmbAnimals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblProductionStatus;
    private javax.swing.JLabel lblTotalCosts;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtNetProfit;
    private javax.swing.JTextField txtTotalCosts;
    private javax.swing.JTextField txtTotalRevenue;
    // End of variables declaration//GEN-END:variables

}
