# -*- coding: utf-8 -*-
"""ProjectTest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9t73fZUxRMavTSorFK98qe8Z9volY4l

# Educational App

## Unit Test

### Integrantes
- Esteban Basurto
- Odalys Chávez
- Daniel Codena

---
"""

# Feature 1: Create Account - Daniel Codena

class User:

    users = []

    def __init__(self, user_id, name, email, password):

        self.user_id = user_id
        self.name = name
        self.email = email
        self.password = password

    def register(self):

        User.users.append(self)

        return True

    def login(self, email, password):

        return (
            self.email == email and
            self.password == password
        )

#Unit Test Feature 1
import unittest

#You can Test Here
TEST_USER = User(
    "U001",
    "Pedro",
    "pedro@test.com",
    "1234"
)


class UserTest(unittest.TestCase):

    def test_name(self):
        self.assertEqual(
            TEST_USER.name,
            "Pedro"
        )

    def test_email(self):
        self.assertEqual(
            TEST_USER.email,
            "pedro@test.com"
        )

    def test_register(self):
        self.assertTrue(
            TEST_USER.register()
        )

    def test_login_success(self):
        self.assertTrue(
            TEST_USER.login(
                "pedro@test.com",
                "1234"
            )
        )

    def test_login_wrong_password(self):
        self.assertFalse(
            TEST_USER.login(
                "pedro@test.com",
                "9999"
            )
        )

suite = unittest.TestLoader().loadTestsFromTestCase(
    UserTest
)

unittest.TextTestRunner(
    verbosity=2
).run(suite)

#Feature 2: Manage Students
class Course:

    def __init__(self, course_id, name, subject):

        self.course_id = course_id
        self.name = name
        self.subject = subject

        self.students = []

    def add_student(self, student):

        if student not in self.students:

            self.students.append(student)

            return True

        return False

    def remove_student(self, student):

        if student in self.students:

            self.students.remove(student)

            return True

        return False

#Unit Test - Feature 2
import unittest

#You Can Test Here
COURSE_ID = "C001"
COURSE_NAME = "Programming Fundamentals"
COURSE_SUBJECT = "Programming"

STUDENT_1 = "Pedro"
STUDENT_2 = "Juan"

class CourseTest(unittest.TestCase):

    def setUp(self):
        self.course = Course(
            COURSE_ID,
            COURSE_NAME,
            COURSE_SUBJECT
        )

        self.student = STUDENT_1
        self.student2 = STUDENT_2


    def test_course_id(self):
        self.assertEqual(
            self.course.course_id,
            "C001"
        )

    def test_course_name(self):
        self.assertEqual(
            self.course.name,
            "Programming Fundamentals"
        )

    def test_student_name(self):
        self.assertEqual(
            self.student,
            "Pedro"
        )

    def test_add_student(self):
        self.assertTrue(
            self.course.add_student(
                self.student
            )
        )

    def test_student_was_added(self):
        self.course.add_student(
            self.student
        )

        self.assertIn(
            self.student,
            self.course.students
        )

    def test_add_duplicate_student(self):
        self.course.add_student(
            self.student
        )

        self.assertFalse(
            self.course.add_student(
                self.student
            )
        )

    def test_remove_student(self):
        self.course.add_student(
            self.student
        )

        self.assertTrue(
            self.course.remove_student(
                self.student
            )
        )

    def test_student_was_removed(self):
        self.course.add_student(
            self.student
        )

        self.course.remove_student(
            self.student
        )

        self.assertNotIn(
            self.student,
            self.course.students
        )

    def test_remove_non_existing_student(self):
        self.assertFalse(
            self.course.remove_student(
                self.student
            )
        )

#Execute Unit Test - Feature 2
suite = unittest.TestLoader().loadTestsFromTestCase(
    CourseTest
)

unittest.TextTestRunner(
    verbosity=2
).run(suite)

#Feature 3: Create Activity
class Activity:

    def __init__(
            self,
            activity_id,
            title,
            description,
            activity_type):

        self.activity_id = activity_id
        self.title = title
        self.description = description
        self.activity_type = activity_type

    def assign(self):

        return True

#Unit test - Feature 3
import unittest

#You Can Test Here
ACTIVITY_ID = "A001"
ACTIVITY_TITLE = "Math Quiz"
ACTIVITY_DESCRIPTION = "Basic Algebra Questions"
ACTIVITY_TYPE = "QUIZa"

class ActivityTest(unittest.TestCase):

    def setUp(self):

        self.activity = Activity(
            ACTIVITY_ID,
            ACTIVITY_TITLE,
            ACTIVITY_DESCRIPTION,
            ACTIVITY_TYPE
        )

    #Data Validation

    def test_activity_id(self):

        self.assertEqual(
            self.activity.activity_id,
            "A001"
        )

    def test_activity_title(self):

        self.assertEqual(
            self.activity.title,
            "Math Quiz"
        )

    def test_activity_type(self):

        self.assertEqual(
            self.activity.activity_type,
            "QUIZ"
        )

    #Functionality

    def test_assign_activity(self):

        self.assertTrue(
            self.activity.assign()
        )

    def test_activity_is_quiz(self):

        self.assertIn(
            self.activity.activity_type,
            ["QUIZ", "RECREATIONAL"]
        )

    def test_title_is_not_empty(self):

        self.assertNotEqual(
            self.activity.title,
            ""
        )

#Execute Unit Test - Feature 3
suite = unittest.TestLoader().loadTestsFromTestCase(
    ActivityTest
)

unittest.TextTestRunner(
    verbosity=2
).run(suite)

#Feature 4
class Grade:
    grades = []

    def __init__(self, student_name, activity_name, score):
        self.student_name = student_name
        self.activity_name = activity_name
        self.score = score

    def save(self):
        Grade.grades.append(self)
        return True

    @staticmethod
    def get_student_grades(student_name):
        result = []
        for g in Grade.grades:
            if g.student_name == student_name:
                result.append(g)
        return result

import unittest
class GradeTest(unittest.TestCase):
    def setUp(self):
        Grade.grades = []

    def test_save_grade(self):
        grade = Grade("Ana", "Quiz 1", 8.5)
        result = grade.save()
        self.assertTrue(result)
        self.assertIn(grade, Grade.grades)
        print("test_save_grade passed")

    def test_get_student_grades(self):
        Grade("Ana", "Quiz 1", 8.5).save()
        Grade("Ana", "Tarea 1", 9.0).save()
        Grade("Luis", "Quiz 1", 7.0).save()

        ana_grades = Grade.get_student_grades("Ana")
        self.assertEqual(len(ana_grades), 2)
        print("test_get_student_grades passed")

    def test_empty_grades(self):
        result = Grade.get_student_grades("Ana")
        self.assertEqual(len(result), 0)
        print(" test_empty_grades passed")

unittest.main(argv=[''], verbosity=2, exit=False)

#Features 5
class Material:
    materials = []

    def __init__(self, title, file_type, url, course):
        self.title = title
        self.file_type = file_type
        self.url = url
        self.course = course

    def upload(self):
        Material.materials.append(self)
        return True

    @staticmethod
    def get_course_materials(course_name):
        result = []
        for m in Material.materials:
            if m.course == course_name:
                result.append(m)
        return result

import unittest

class MaterialTest(unittest.TestCase):

    def setUp(self):
        Material.materials = []

    def test_upload_math(self):
        Material("Algebra", "PDF", "url", "Math").upload()
        self.assertEqual(len(Material.get_course_materials("Math")), 1)
        print("Math works")

    def test_upload_language(self):
        Material("Spelling", "PDF", "url", "Language").upload()
        self.assertEqual(len(Material.get_course_materials("Language")), 1)


    def test_upload_music(self):
        Material("Musical Notes", "VIDEO", "url", "Music").upload()
        self.assertEqual(len(Material.get_course_materials("Music")), 1)


    def test_multiple_subjects(self):
        Material("Math 1", "PDF", "u1", "Math").upload()
        Material("Language 1", "PDF", "u2", "Language").upload()
        Material("Music 1", "PDF", "u3", "Music").upload()

        self.assertEqual(len(Material.get_course_materials("Math")), 1)
        self.assertEqual(len(Material.get_course_materials("Language")), 1)
        self.assertEqual(len(Material.get_course_materials("Music")), 1)


    def test_no_materials(self):
        result = Material.get_course_materials("Empty Course")
        self.assertEqual(len(result), 0)


unittest.main(argv=[''], verbosity=2, exit=False)

#Feature 8
class Participation:
    participations = []

    def __init__(self, student_name, activity_name,course,  date, participation_score):
        self.student_name = student_name
        self.activity_name = activity_name
        self.course = course
        self.date = date
        self.participation_score = participation_score

    def record(self):
        Participation.participations.append(self)
        return True

    @staticmethod
    def get_student_participation(student_name):
        return [p for p in Participation.participations if p.student_name == student_name]


    @staticmethod
    def get_average_participation(student_name):
        student_parts = Participation.get_student_participation(student_name)
        if not student_parts:
            return 0
        return sum(p.participation_score for p in student_parts) / len(student_parts)

    @staticmethod
    def get_low_participation_students(course_name, threshold=5):
        course_parts = Participation.get_course_participation(course_name)
        student_scores = {}
        for p in course_parts:
            if p.student_name not in student_scores:
                student_scores[p.student_name] = []
            student_scores[p.student_name].append(p.participation_score)

        return [(student, sum(scores)/len(scores)) for student, scores in student_scores.items()
                if (sum(scores)/len(scores)) < threshold]


import unittest

class ParticipationTest(unittest.TestCase):

    def setUp(self):
        Participation.participations = []

    def test_record_participation(self):
        p = Participation("Emma", "Quiz", "Math", "2026-06-01", 9)
        result = p.record()
        self.assertTrue(result)
        self.assertIn(p, Participation.participations)

    def test_get_student_participation(self):
        Participation("Emma", "Quiz 1", "Math", "2026-06-01", 9).record()
        Participation("Emma", "Quiz 2", "Math", "2026-06-02", 8).record()
        self.assertEqual(len(Participation.get_student_participation("Emma")), 2)

    def test_average_participation(self):
        Participation("Emma", "Quiz 1", "Math", "2026-06-01", 9).record()
        Participation("Emma", "Quiz 2", "Math", "2026-06-02", 10).record()
        self.assertEqual(Participation.get_average_participation("Emma"), 9.5)

    def test_low_participation(self):
        Participation("Emma", "Quiz", "Math", "2026-06-01", 9).record()
        Participation("Oliver", "Quiz", "Math", "2026-06-01", 4).record()
        low = Participation.get_low_participation_students("Math", threshold=6)
        self.assertEqual(len(low), 1)
        self.assertEqual(low[0][0], "Oliver")

    def test_empty_participation(self):
        self.assertEqual(len(Participation.get_student_participation("Unknown")), 0)

    def test_course_participation(self):
        Participation("Emma", "Quiz", "Math", "2026-06-01", 9).record()
        Participation("Emma", "Quiz", "Music", "2026-06-01", 9).record()
        self.assertEqual(len(Participation.get_course_participation("Math")), 1)
        self.assertEqual(len(Participation.get_course_participation("Music")), 1)


if __name__ == "__main__":
    unittest.main(argv=[''], verbosity=2, exit=False)