/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mothersApp.view.gui;

import ec.edu.espe.mothersApp.controller.EducationalResourceController;


/**
 *
 * @author sbart
 */
public class EducationalResource extends javax.swing.JFrame {
    private int currentTipIndex = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EducationalResource.class.getName());
        private EducationalResourceController controller;
    public EducationalResource() {
        initComponents();
        this.controller = new ec.edu.espe.mothersApp.controller.EducationalResourceController();
        updateTipCard();
    }
    private void updateTipCard() {
    int selectedTopic = cmbTopics.getSelectedIndex();
    
    String tipText = controller.getTipContent(selectedTopic, currentTipIndex);
    String alertLevel = controller.getAlertLevel(selectedTopic, currentTipIndex);
    int totalTips = controller.getTipsCount(selectedTopic);
    
    lblTipNumber.setText("TIP " + (currentTipIndex + 1));
    txtTipContent.setText(tipText);
    lblProgress.setText("Tip " + (currentTipIndex + 1) + " de " + totalTips);
    
    switch (alertLevel) {
        case "DANGER":
            pnlCard.setBackground(new java.awt.Color(255, 204, 204)); // Rojo suave
            txtTipContent.setBackground(new java.awt.Color(255, 204, 204));
            lblTipNumber.setForeground(java.awt.Color.RED);
            break;
            
        case "WARNING":
            pnlCard.setBackground(new java.awt.Color(255, 255, 204)); // Amarillo suave
            txtTipContent.setBackground(new java.awt.Color(255, 255, 204));
            lblTipNumber.setForeground(new java.awt.Color(204, 102, 0));
            break;
            
        default: // "NORMAL"
            pnlCard.setBackground(new java.awt.Color(204, 229, 255)); // Azul suave
            txtTipContent.setBackground(new java.awt.Color(204, 229, 255));
            lblTipNumber.setForeground(new java.awt.Color(0, 51, 102));
            break;
    }
    
    btnPrevious.setEnabled(currentTipIndex > 0);
    btnNext.setEnabled(currentTipIndex < totalTips - 1);
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTopics = new javax.swing.JComboBox<>();
        pnlCard = new javax.swing.JPanel();
        lblTipNumber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTipContent = new javax.swing.JTextArea();
        lblProgress = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("EDUCATIONAL TIPS FOR PARENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cmbTopics.setBackground(new java.awt.Color(153, 255, 204));
        cmbTopics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baby does not sleep", " ", "Baby does not latch", " ", "How to burp baby", " ", "Crying constantly", " ", "Umbilical cord care" }));
        cmbTopics.addActionListener(this::cmbTopicsActionPerformed);

        pnlCard.setBackground(new java.awt.Color(230, 250, 240));
        pnlCard.setBorder(javax.swing.BorderFactory.createTitledBorder("Advice for Parents"));

        lblTipNumber.setText("TIP 1");

        txtTipContent.setEditable(false);
        txtTipContent.setBackground(new java.awt.Color(234, 241, 237));
        txtTipContent.setColumns(20);
        txtTipContent.setRows(5);
        txtTipContent.setWrapStyleWord(true);
        txtTipContent.setOpaque(false);
        jScrollPane1.setViewportView(txtTipContent);

        javax.swing.GroupLayout pnlCardLayout = new javax.swing.GroupLayout(pnlCard);
        pnlCard.setLayout(pnlCardLayout);
        pnlCardLayout.setHorizontalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addComponent(lblTipNumber)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCardLayout.setVerticalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTipNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblProgress.setText("TIP 2");

        btnPrevious.setText("Former");
        btnPrevious.addActionListener(this::btnPreviousActionPerformed);

        btnNext.setText("Next");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnBack.setText("Return to Menu");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblProgress)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addGap(101, 101, 101)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(cmbTopics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbTopics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgress)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnBack))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbTopicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTopicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTopicsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EducationalResource().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox<String> cmbTopics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblTipNumber;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JTextArea txtTipContent;
    // End of variables declaration//GEN-END:variables
}
