/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.oopconcepts.view;

import ec.edu.espe.oopconcepts.controller.AnimalController;
import ec.edu.espe.oopconcepts.controller.CutController;
import ec.edu.espe.oopconcepts.controller.FoodController;
import ec.edu.espe.oopconcepts.model.*;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Codena, CodeBreakers, @ESPE
 */
public class FrmAnimalOperations extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAnimalOperations.class.getName());

    /**
     * Creates new form FrmAnimalOperations
     */
    public FrmAnimalOperations() {
        initComponents();

        loadAnimalTable();
        loadFoodComboBox();
        loadCutsTable();
    }

    public void loadAnimalTable() {

        AnimalController controller = new AnimalController();
        ArrayList<FarmAnimal> animals = controller.read();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Type");
        model.addColumn("Breed");
        model.addColumn("Birth");
        model.addColumn("Weight");

        for (FarmAnimal animal : animals) {

            model.addRow(new Object[]{
                animal.getId(),
                animal.getClass().getSimpleName(),
                animal.getBreed(),
                animal.getBornOnDate(),
                animal.getWeight()

            });

        }

        tblAnimals.setModel(model);
    }

    public void loadCutsTable() {
        CutController controller = new CutController();
        ArrayList<Cut> cuts = controller.read();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Description");
        model.addColumn("Procedure");
        model.addColumn("Weight");

        for (Cut cut : cuts) {
            model.addRow(new Object[]{
                cut.getDescription(),
                cut.getProcedure(),
                cut.getWeight()
            });
        }

        tblCuts.setModel(model);

    }

    public void loadAnimal() {

        AnimalController controller = new AnimalController();
        int id = Integer.parseInt(lblId.getText());

        FarmAnimal animal = controller.findById(id);

        if (animal instanceof Chicken) {

            Chicken chicken = (Chicken) animal;
            int numberOfEggs = chicken.getNumberOfEggs();

            lblNumerOfEggs.setText(String.valueOf(numberOfEggs));
            if (chicken.isMolting()) {
                lblIsMolting.setText("True");
            } else {
                lblIsMolting.setText("False");
            }

        } else if (animal instanceof Cow) {
            Cow cow = (Cow) animal;
            if (cow.isIsProducingMilk()) {
                lblIsProducingMilk.setText("True");
            } else {
                lblIsProducingMilk.setText("False");
            }
        } else if (animal instanceof Sheep) {
            Sheep sheep = (Sheep) animal;
            LocalDate lastShearing = sheep.getLastShearing();
            lblLastShearing.setText(lastShearing.toString());
        } else if (animal instanceof Pig) {
            Pig pig = (Pig) animal;
            float weight = pig.getWeight();
            float idealWeight = pig.getIdealWeight();

            lblIdealWeight.setText(String.valueOf(idealWeight));
            lblWeight.setText(String.valueOf(weight));
        }

    }

    private void loadFoodComboBox() {

        cmbFood.removeAllItems();

        FoodController controller = new FoodController();

        ArrayList<Food> foods = controller.read();

        for (Food food : foods) {
            cmbFood.addItem(food);
        }

    }

    public void clear() {
        lblId.setText("-");
        lblTypeOfAnimal.setText("-");
        lblAgeInMonths.setText("-");

        lblIsMolting.setText("-");
        lblNumerOfEggs.setText("-");

        lblIsProducingMilk.setText("-");

        lblLastShearing.setText("-");

        lblIdealWeight.setText("-");
        lblWeight.setText("-");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTypeOfAnimal = new javax.swing.JLabel();
        btnFeed = new javax.swing.JButton();
        btnCalculateAgeInMonths = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblAgeInMonths = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbFood = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimals = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCuts = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();
        pnlSpecific = new javax.swing.JPanel();
        pnlChicken = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNumerOfEggs = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblIsMolting = new javax.swing.JLabel();
        btnLayAnEgg = new javax.swing.JButton();
        pnlCow = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblIsProducingMilk = new javax.swing.JLabel();
        btnMilk = new javax.swing.JButton();
        btnCutCow = new javax.swing.JButton();
        pnlSheep = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblLastShearing = new javax.swing.JLabel();
        pnlPig = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblIdealWeight = new javax.swing.JLabel();
        btnCutPig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Animal Operations");

        jLabel2.setText("Id:");

        lblId.setText("-");

        jLabel3.setText("Type of Animal:");

        lblTypeOfAnimal.setText("-");
        lblTypeOfAnimal.addPropertyChangeListener(this::lblTypeOfAnimalPropertyChange);

        btnFeed.setText("Feed");
        btnFeed.addActionListener(this::btnFeedActionPerformed);

        btnCalculateAgeInMonths.setText("Calcultate");
        btnCalculateAgeInMonths.addActionListener(this::btnCalculateAgeInMonthsActionPerformed);

        jLabel14.setText("Calculate Age in Months:");

        lblAgeInMonths.setText("-");

        jLabel15.setText("Avaible food:");

        javax.swing.GroupLayout pnlGeneralLayout = new javax.swing.GroupLayout(pnlGeneral);
        pnlGeneral.setLayout(pnlGeneralLayout);
        pnlGeneralLayout.setHorizontalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(152, 152, 152))
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlGeneralLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cmbFood, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFeed, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlGeneralLayout.createSequentialGroup()
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTypeOfAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlGeneralLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(lblAgeInMonths, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculateAgeInMonths)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGeneralLayout.setVerticalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeneralLayout.createSequentialGroup()
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlGeneralLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFeed))
                    .addGroup(pnlGeneralLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblTypeOfAnimal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblAgeInMonths)
                            .addComponent(btnCalculateAgeInMonths))
                        .addGap(37, 37, 37)
                        .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cmbFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );

        tblAnimals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnimals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnimalsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnimals);

        tblCuts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCuts);

        jLabel16.setText("Cut Table");

        jLabel17.setText("Animal Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBackToMenu.setText("Back To Menu");
        btnBackToMenu.addActionListener(this::btnBackToMenuActionPerformed);

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToMenu)
                .addGap(38, 38, 38))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnBackToMenu))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlSpecific.setLayout(new java.awt.CardLayout());

        jLabel4.setText("Chicken");

        jLabel8.setText("Number Of Eggs:");

        lblNumerOfEggs.setText("-");

        jLabel9.setText("Is Molting:");

        lblIsMolting.setText("-");

        btnLayAnEgg.setText("Lay An Egg");
        btnLayAnEgg.addActionListener(this::btnLayAnEggActionPerformed);

        javax.swing.GroupLayout pnlChickenLayout = new javax.swing.GroupLayout(pnlChicken);
        pnlChicken.setLayout(pnlChickenLayout);
        pnlChickenLayout.setHorizontalGroup(
            pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChickenLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(184, 184, 184))
            .addGroup(pnlChickenLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLayAnEgg)
                    .addGroup(pnlChickenLayout.createSequentialGroup()
                        .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIsMolting, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(lblNumerOfEggs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChickenLayout.setVerticalGroup(
            pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChickenLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblNumerOfEggs))
                .addGap(18, 18, 18)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblIsMolting))
                .addGap(32, 32, 32)
                .addComponent(btnLayAnEgg)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pnlSpecific.add(pnlChicken, "Chicken");

        jLabel5.setText("Cow");

        jLabel10.setText("Is Producing milk:");

        lblIsProducingMilk.setText("-");

        btnMilk.setText("Milk");
        btnMilk.addActionListener(this::btnMilkActionPerformed);

        btnCutCow.setText("Cut");
        btnCutCow.addActionListener(this::btnCutCowActionPerformed);

        javax.swing.GroupLayout pnlCowLayout = new javax.swing.GroupLayout(pnlCow);
        pnlCow.setLayout(pnlCowLayout);
        pnlCowLayout.setHorizontalGroup(
            pnlCowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCowLayout.createSequentialGroup()
                .addGroup(pnlCowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCowLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCowLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnlCowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMilk)
                            .addGroup(pnlCowLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(lblIsProducingMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCutCow))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        pnlCowLayout.setVerticalGroup(
            pnlCowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCowLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(pnlCowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblIsProducingMilk))
                .addGap(18, 18, 18)
                .addComponent(btnMilk)
                .addGap(47, 47, 47)
                .addComponent(btnCutCow)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pnlSpecific.add(pnlCow, "Cow");

        jLabel6.setText("Sheep");

        jLabel11.setText("Last Shearing:");

        lblLastShearing.setText("-");

        javax.swing.GroupLayout pnlSheepLayout = new javax.swing.GroupLayout(pnlSheep);
        pnlSheep.setLayout(pnlSheepLayout);
        pnlSheepLayout.setHorizontalGroup(
            pnlSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSheepLayout.createSequentialGroup()
                .addGroup(pnlSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSheepLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSheepLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblLastShearing, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlSheepLayout.setVerticalGroup(
            pnlSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSheepLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(pnlSheepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblLastShearing))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        pnlSpecific.add(pnlSheep, "Sheep");

        jLabel7.setText("Pig");

        jLabel12.setText("Weight:");

        jLabel13.setText("Ideal Weight:");

        lblWeight.setText("-");

        lblIdealWeight.setText("-");

        btnCutPig.setText("Cut");
        btnCutPig.addActionListener(this::btnCutPigActionPerformed);

        javax.swing.GroupLayout pnlPigLayout = new javax.swing.GroupLayout(pnlPig);
        pnlPig.setLayout(pnlPigLayout);
        pnlPigLayout.setHorizontalGroup(
            pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPigLayout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(197, 197, 197))
            .addGroup(pnlPigLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPigLayout.createSequentialGroup()
                        .addGroup(pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(lblIdealWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnCutPig))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPigLayout.setVerticalGroup(
            pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPigLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblWeight))
                .addGap(18, 18, 18)
                .addGroup(pnlPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblIdealWeight))
                .addGap(34, 34, 34)
                .addComponent(btnCutPig)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pnlSpecific.add(pnlPig, "Pig");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSpecific, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSpecific, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAnimalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnimalsMouseClicked

        int row = tblAnimals.getSelectedRow();

        lblId.setText(tblAnimals.getValueAt(row, 0).toString());
        lblTypeOfAnimal.setText(tblAnimals.getValueAt(row, 1).toString());

        loadAnimal();
    }//GEN-LAST:event_tblAnimalsMouseClicked

    private void lblTypeOfAnimalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblTypeOfAnimalPropertyChange

        CardLayout card = (CardLayout) pnlSpecific.getLayout();
        String type = lblTypeOfAnimal.getText();

        card.show(pnlSpecific, type);


    }//GEN-LAST:event_lblTypeOfAnimalPropertyChange

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLayAnEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayAnEggActionPerformed

        if (lblId.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Select a chicken");
            return;
        }

        int id = Integer.parseInt(lblId.getText());

        AnimalController controller = new AnimalController();
        FarmAnimal animal = controller.findById(id);
        Chicken chicken = (Chicken) animal;

        if (chicken.layAnEgg()) {
            JOptionPane.showMessageDialog(this, "Chicken " + lblId.getText() + " cannot lay an egg");
        } else {
            controller.update(chicken);
            JOptionPane.showMessageDialog(this, "Chicken " + lblId.getText() + " layed an egg");
            loadAnimal();
            loadAnimalTable();
        }
    }//GEN-LAST:event_btnLayAnEggActionPerformed

    private void btnCutPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCutPigActionPerformed
        if (lblId.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Select a pig");
            return;
        }

        AnimalController animalController = new AnimalController();
        CutController cutController = new CutController();

        int id = Integer.parseInt(lblId.getText());
        FarmAnimal animal = animalController.findById(id);
        Pig pig = (Pig) animal;

        if (pig.sendToButcher()) {
            ArrayList<Cut> cuts = pig.cut();

            for (Cut cut : cuts) {
                cutController.create(cut);
            }

            animalController.delete(id);
            JOptionPane.showMessageDialog(this, "Pig " + String.valueOf(id) + " died, 3 new cuts have been added");
            loadAnimalTable();
            loadCutsTable();
            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Pig has not been sent to butcher, The weight is lower than the ideal weight");
        }


    }//GEN-LAST:event_btnCutPigActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        FrmMenu frmMenu = new FrmMenu();
        frmMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedActionPerformed
        if (lblId.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Select an Animal");
            return;
        }
        AnimalController animalController = new AnimalController();
        FoodController foodController = new FoodController();

        int id = Integer.parseInt(lblId.getText());
        Food selectedFood = (Food) cmbFood.getSelectedItem();
        FarmAnimal animal = animalController.findById(id);

        if (animal.feed(selectedFood)) {
            animalController.update(animal);
            foodController.delete(selectedFood.getId());

            loadAnimalTable();
            loadAnimal();
            loadFoodComboBox();
        } else {
            JOptionPane.showMessageDialog(this, "You cannot feed this animal with " + selectedFood.getTypeOfFood());
        }

    }//GEN-LAST:event_btnFeedActionPerformed

    private void btnMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilkActionPerformed
        if (lblId.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Select an Animal");
            return;
        }

        int id = Integer.parseInt(lblId.getText());

        AnimalController animalController = new AnimalController();
        FarmAnimal animal = animalController.findById(id);

        Cow cow = (Cow) animal;

        if (cow.isIsProducingMilk()) {
            JOptionPane.showMessageDialog(this, cow.toString());
        } else {
            JOptionPane.showMessageDialog(this, "This cow cannot produce milk");
        }
    }//GEN-LAST:event_btnMilkActionPerformed

    private void btnCutCowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCutCowActionPerformed
        if (lblId.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Select a cow");
            return;
        }

        AnimalController animalController = new AnimalController();
        CutController cutController = new CutController();

        int id = Integer.parseInt(lblId.getText());
        FarmAnimal animal = animalController.findById(id);
        Cow cow = (Cow) animal;

        ArrayList<Cut> cuts = cow.cut();

        for (Cut cut : cuts) {
            cutController.create(cut);
        }

        animalController.delete(id);
        JOptionPane.showMessageDialog(this, "Cow " + String.valueOf(id) + " died, 3 new cuts have been added");
        loadAnimalTable();
        loadCutsTable();
        clear();
    }//GEN-LAST:event_btnCutCowActionPerformed

    private void btnCalculateAgeInMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateAgeInMonthsActionPerformed
        if (lblId.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Select an animal");
            return;
        }
        AnimalController controller = new AnimalController();

        int id = Integer.parseInt(lblId.getText());

        FarmAnimal animal = controller.findById(id);

        int ageInMonths = animal.getAgeInMonths();
        lblAgeInMonths.setText(String.valueOf(ageInMonths));

    }//GEN-LAST:event_btnCalculateAgeInMonthsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAnimalOperations().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnCalculateAgeInMonths;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCutCow;
    private javax.swing.JButton btnCutPig;
    private javax.swing.JButton btnFeed;
    private javax.swing.JButton btnLayAnEgg;
    private javax.swing.JButton btnMilk;
    private javax.swing.JComboBox<Food> cmbFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgeInMonths;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdealWeight;
    private javax.swing.JLabel lblIsMolting;
    private javax.swing.JLabel lblIsProducingMilk;
    private javax.swing.JLabel lblLastShearing;
    private javax.swing.JLabel lblNumerOfEggs;
    private javax.swing.JLabel lblTypeOfAnimal;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlChicken;
    private javax.swing.JPanel pnlCow;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JPanel pnlPig;
    private javax.swing.JPanel pnlSheep;
    private javax.swing.JPanel pnlSpecific;
    private javax.swing.JTable tblAnimals;
    private javax.swing.JTable tblCuts;
    // End of variables declaration//GEN-END:variables
}
