# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1je-zgOYvXCVmV6K6-qVT715s8ID_N67o
"""

import random

def run_multiplication_test(num1, num2, correct_answer, test_id):
    # Assuming 'correct_answer' is the pre-calculated expected result
    print(f"Test {test_id}: {num1} * {num2} = {correct_answer} (Correct)")

for i in range(1, 6):
    num1 = round(random.uniform(1, 10), 2)
    num2 = round(random.uniform(1, 10), 2)
    correct_answer = round(num1 * num2, 2)
    run_multiplication_test(num1, num2, correct_answer, i)

def run_division_test(num1, num2, user_answer, test_id):
    correct_answer = round(num1 / num2, 2)
    if user_answer == correct_answer:
        print(f"Test {test_id}: {num1} / {num2} = {user_answer} (Correct)")
    else:
        print(f"Test {test_id}: {num1} / {num2} = {user_answer} (Incorrect). The correct answer was {correct_answer}")

print("\n--- 5 correct operations ---")

for i in range(1, 6):
    num1 = round(random.uniform(1, 50), 2)
    num2 = round(random.uniform(1, 25), 2)
    correct_answer = round(num1 / num2, 2)
    run_division_test(num1, num2, correct_answer, i)

#Daniel
class SubtractOperation:
  @staticmethod
  def subtract(minuend, subtrahend):
    difference = minuend - subtrahend
    return difference

#Daniel
import unittest

class SubtractTest(unittest.TestCase):
  def test_subtract(self):
    minuend = 3.6
    subtrahend = 1.2
    expected_result = 2.4
    result = SubtractOperation.subtract(minuend, subtrahend)

    self.assertAlmostEqual(result, expected_result, places=2)

if __name__ == '__main__':
    unittest.main(argv=[''], exit=False)

#Daniel
suite = unittest.TestLoader().loadTestsFromTestCase(SubtractTest)

unittest.TextTestRunner(verbosity=2).run(suite)

import unittest

class AddOperation:

    @staticmethod
    def add(addend1, addend2):
        sum = addend1 + addend2
        return sum


class AddTest(unittest.TestCase):

    def test_add(self):
        addend1 = 3.5
        addend2 = 2.4
        expected_result = 5.9

        result = AddOperation.add(addend1, addend2)

        self.assertAlmostEqual(expected_result, result, places=1)


unittest.main(argv=[''], exit=False)